version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8-bugbear
    versions:
    - 21.3.1
    - 21.3.2
